---
title: "Final Project"
authors: "Tatum Good, Jace Higa, Kendall Leonard"
format: 
  revealjs:
      embed-resources: true
      mainfont: Century Schoolbook
      slide-number: true
editor: visual

---

## What's the point of it all

- Same as everyone else
    - get the smallest RMSE



- But what does that even mean in this context?
  - Answer: have a model who is off by the lowest amount when predicting profit


## Scrub-a-dub-dub (AKA Cleaning the Data)

- A lot of percentages in this data
  - meaning that a lot of numeric data was being seen as textual, making any meaningful feature building next to impossible
  
- So we chopped off the percentages!
  - Yay! Workable data!

## Features We Used {.smaller}

   - bel_avg_BOM
   - high_revenue 
   - log_revenue 
   - interaction_cost_units 
   - high_volume 
   - src_www 
   - direct 
   - form 
   - finish 
   - year_min 

## A detailed look: bel_94_perc_BOM
- Stands for 'Below the 94th Percentile BOM (Bill of Materials)'
- Bill of Materials: A price that consists of all materials needed to assemble a product.
  - The less the materials cost, the more profit is possible.
- Why the 94th percentile?
  - Tested many percentiles but the 94th ended up lowering our RMSE the most.

## A detailed look: high_revenue_products
- Used the 94th percentile as well.
  - Figured that the more potential revenue you make off of a product the more profit is available.
  - Think selling a house vs. selling hotdogs

## A detailed look: log_revenue 

## A detailed look: interaction_cost_units 

## A detailed look: high_volume 
- Used the 99th percentile as well.
  - Think back to the selling a house vs. selling hotdogs analogy
  - If you sell ten thousand hotdogs there is more room for profit which is where this idea came from

## A detailed look: direct 
## A detailed look: form
## A detailed look: finish 
## A detailed look: year_min 
## A detailed look: Design of Model
## A detailed look: RMSE Reveal
## Thank you!
